import type { Lang } from "../LanguageContext";

interface AIDisclosureContent {
  eyebrow: string;
  title: string;
  intro: string;
  // Section 1: where
  whereTitle: string;
  whereIntro: string;
  aiRepliesLabel: string;
  aiRepliesDesc: string;
  aiConvosLabel: string;
  aiConvosDesc: string;
  // Section 2: static
  staticTitle: string;
  staticBody: string;
  // Section 3: signature
  signatureTitle: string;
  signatureBeforeQuote: string;
  signatureQuote: string;
  signatureAfterQuote: string;
  // Section 4: what AI sees
  seesTitle: string;
  seesBullets: string[];
  seesFooter: string;
  // Section 5: guardrails
  safetyTitle: string;
  safetyBullets: string[];
  // Section 6: providers
  providersTitle: string;
  providersBefore: string;
  providersLink: string;
  providersAfter: string;
  // Section 7: reporting
  reportTitle: string;
  reportBefore: string;
  reportAfter: string;
}

export const aiDisclosure: Record<Lang, AIDisclosureContent> = {
  en: {
    eyebrow: "AI Disclosure",
    title: "How LightChats uses AI",
    intro:
      "Transparency about where AI is involved in the messages your followers receive, what data the AI sees, and the safeguards in place — required by Meta's AI Messaging policy and by us.",
    whereTitle: "Where AI is used",
    whereIntro:
      "LightChats uses Anthropic's Claude models to generate two specific kinds of outbound messages:",
    aiRepliesLabel: "AI replies",
    aiRepliesDesc:
      "single-turn responses to comments or DMs, generated from a creator's configured prompt and brand voice.",
    aiConvosLabel: "AI conversations",
    aiConvosDesc:
      "multi-turn DM threads where the AI follows the creator's instructions to qualify, support, or convert a contact.",
    staticTitle: "Static replies are not AI",
    staticBody:
      'Pre-written templates ("static replies") are sent verbatim. They are not generated by AI. The vast majority of high-volume flows run on static replies.',
    signatureTitle: "How recipients know",
    signatureBeforeQuote: "On the Free plan, every automated outbound DM includes a ",
    signatureQuote: '"— Sent via LightChats ⚡"',
    signatureAfterQuote:
      " signature so recipients can identify the source. Paid plans remove the signature; creators on paid plans are responsible for disclosing AI involvement to their audience as their local laws require (e.g., EU AI Act, California SB-1001).",
    seesTitle: "What the AI sees",
    seesBullets: [
      "The incoming message and a short rolling window of prior messages in the same conversation",
      "The creator's configured prompt, brand voice, and goals",
      "Optional context the creator has configured (e.g., FAQ, product list)",
    ],
    seesFooter:
      "The AI does not see other contacts' conversations, billing data, or any data outside the LightChats workspace it's invoked from.",
    safetyTitle: "Safety guardrails",
    safetyBullets: [
      "A safety prompt that prevents the AI from making medical, legal, or financial guarantees, impersonating real people, or generating discriminatory content",
      "Hard limits on outbound message frequency to prevent spam behavior on Instagram",
      'Manual override and "stop AI for this contact" controls available to the creator at any time',
      "AI usage is metered and capped by plan — nothing happens silently",
    ],
    providersTitle: "Model providers and data handling",
    providersBefore:
      "Inference runs on Anthropic's Claude API. Per Anthropic's policy, prompts and responses are not used to train Anthropic's models. LightChats stores the AI's response in your workspace alongside the conversation; you can delete that data via the Inbox or via ",
    providersLink: "full account deletion",
    providersAfter: ".",
    reportTitle: "Reporting issues",
    reportBefore:
      "If you receive an AI-generated message you believe is harmful, misleading, or violates Instagram's policies, please report it to ",
    reportAfter:
      ". We investigate every report and disable the offending workflow while we review.",
  },
  fr: {
    eyebrow: "Divulgation IA",
    title: "Comment LightChats utilise l'IA",
    intro:
      "Transparence sur les endroits où l'IA intervient dans les messages reçus par vos abonnés, sur les données qu'elle voit et sur les garde-fous en place — exigé par la politique de messagerie IA de Meta et par nous.",
    whereTitle: "Où l'IA est utilisée",
    whereIntro:
      "LightChats utilise les modèles Claude d'Anthropic pour générer deux types précis de messages sortants :",
    aiRepliesLabel: "Réponses IA",
    aiRepliesDesc:
      "réponses en un seul tour à des commentaires ou des DM, générées à partir du prompt configuré et de la voix de marque du créateur.",
    aiConvosLabel: "Conversations IA",
    aiConvosDesc:
      "échanges multi-tours en DM où l'IA suit les instructions du créateur pour qualifier, accompagner ou convertir un contact.",
    staticTitle: "Les réponses statiques ne sont pas de l'IA",
    staticBody:
      "Les modèles prérédigés (« réponses statiques ») sont envoyés tels quels. Ils ne sont pas générés par l'IA. La grande majorité des flux à fort volume reposent sur des réponses statiques.",
    signatureTitle: "Comment les destinataires le savent",
    signatureBeforeQuote:
      "Sur le plan Gratuit, chaque DM sortant automatisé inclut une signature ",
    signatureQuote: '« — Envoyé via LightChats ⚡ »',
    signatureAfterQuote:
      " afin que les destinataires puissent identifier la source. Les plans payants suppriment la signature ; les créateurs aux plans payants sont responsables de la divulgation de l'usage de l'IA auprès de leur audience, comme l'exige leur droit local (par ex. EU AI Act, California SB-1001).",
    seesTitle: "Ce que l'IA voit",
    seesBullets: [
      "Le message entrant et un court fil glissant des messages précédents de la même conversation",
      "Le prompt configuré par le créateur, sa voix de marque et ses objectifs",
      "Le contexte optionnel configuré par le créateur (par ex. FAQ, liste de produits)",
    ],
    seesFooter:
      "L'IA ne voit pas les conversations des autres contacts, ni les données de facturation, ni aucune donnée extérieure à l'espace de travail LightChats depuis lequel elle est invoquée.",
    safetyTitle: "Garde-fous de sécurité",
    safetyBullets: [
      "Un prompt de sécurité qui empêche l'IA de faire des promesses médicales, juridiques ou financières, d'usurper l'identité de personnes réelles ou de produire des contenus discriminatoires",
      "Des limites strictes sur la fréquence des messages sortants pour prévenir tout comportement de spam sur Instagram",
      "Des contrôles d'arrêt manuel et « stopper l'IA pour ce contact » disponibles à tout moment pour le créateur",
      "L'usage de l'IA est mesuré et plafonné selon le plan — rien ne se passe en silence",
    ],
    providersTitle: "Fournisseurs de modèles et traitement des données",
    providersBefore:
      "L'inférence s'exécute via l'API Claude d'Anthropic. Selon la politique d'Anthropic, les prompts et les réponses ne servent pas à entraîner les modèles d'Anthropic. LightChats enregistre la réponse de l'IA dans votre espace de travail à côté de la conversation ; vous pouvez supprimer ces données depuis la boîte de réception ou via la ",
    providersLink: "suppression complète du compte",
    providersAfter: ".",
    reportTitle: "Signaler un problème",
    reportBefore:
      "Si vous recevez un message généré par l'IA que vous jugez nuisible, trompeur ou contraire aux règles d'Instagram, signalez-le à ",
    reportAfter:
      ". Nous enquêtons sur chaque signalement et désactivons le flux fautif pendant l'examen.",
  },
  ar: {
    eyebrow: "إفصاح الذكاء الاصطناعي",
    title: "كيف يستخدم LightChats الذكاء الاصطناعي",
    intro:
      "شفافية حول المواضع التي يتدخل فيها الذكاء الاصطناعي في الرسائل التي يتلقاها متابعوك، والبيانات التي يراها، والضمانات المعمول بها — وفقاً لسياسة Meta للرسائل بالذكاء الاصطناعي ولسياستنا.",
    whereTitle: "أين يُستخدم الذكاء الاصطناعي",
    whereIntro:
      "يستخدم LightChats نماذج Claude من Anthropic لتوليد نوعين محددين من الرسائل الصادرة:",
    aiRepliesLabel: "ردود الذكاء الاصطناعي",
    aiRepliesDesc:
      "ردود من دورة واحدة على التعليقات أو الرسائل المباشرة، تُولَّد من المُوجِّه الذي ضبطه المبدع وصوت علامته التجارية.",
    aiConvosLabel: "محادثات الذكاء الاصطناعي",
    aiConvosDesc:
      "محادثات DM متعددة الدورات يتبع فيها الذكاء الاصطناعي تعليمات المبدع لتأهيل جهة الاتصال أو دعمها أو تحويلها إلى عميل.",
    staticTitle: "الردود الثابتة ليست ذكاءً اصطناعياً",
    staticBody:
      'القوالب المُعدّة مسبقاً ("الردود الثابتة") تُرسَل كما هي. وهي ليست مولَّدة بالذكاء الاصطناعي. تعتمد الغالبية العظمى من التدفقات عالية الحجم على الردود الثابتة.',
    signatureTitle: "كيف يعرف المستلمون",
    signatureBeforeQuote:
      "في الباقة المجانية، كل رسالة مباشرة آلية صادرة تتضمن توقيع ",
    signatureQuote: '"— Sent via LightChats ⚡"',
    signatureAfterQuote:
      " ليتمكن المستلم من التعرف على المصدر. تُزيل الباقات المدفوعة هذا التوقيع؛ ويتحمّل المبدعون في الباقات المدفوعة مسؤولية الإفصاح عن استخدام الذكاء الاصطناعي لجمهورهم وفق ما تُلزمهم به القوانين المحلية (مثل EU AI Act وCalifornia SB-1001).",
    seesTitle: "ما يراه الذكاء الاصطناعي",
    seesBullets: [
      "الرسالة الواردة ونافذة قصيرة متحركة من الرسائل السابقة في المحادثة ذاتها",
      "المُوجِّه المضبوط من المبدع وصوت علامته التجارية وأهدافه",
      "السياق الاختياري الذي ضبطه المبدع (مثل الأسئلة الشائعة وقائمة المنتجات)",
    ],
    seesFooter:
      "لا يرى الذكاء الاصطناعي محادثات جهات الاتصال الأخرى ولا بيانات الفوترة ولا أي بيانات خارج مساحة عمل LightChats التي استُدعي منها.",
    safetyTitle: "ضمانات السلامة",
    safetyBullets: [
      "موجّه سلامة يمنع الذكاء الاصطناعي من تقديم ضمانات طبية أو قانونية أو مالية أو انتحال شخصيات حقيقية أو إنتاج محتوى تمييزي",
      "حدود صارمة على وتيرة الرسائل الصادرة لمنع سلوك السبام على إنستغرام",
      'إمكانية التدخل اليدوي وأزرار "إيقاف الذكاء الاصطناعي لهذه الجهة" متاحة للمبدع في أي وقت',
      "استخدام الذكاء الاصطناعي مُقاس ومُحدَّد وفق الباقة — لا شيء يحدث بصمت",
    ],
    providersTitle: "مزوّدو النماذج وإدارة البيانات",
    providersBefore:
      "يتم الاستدلال عبر واجهة Claude API من Anthropic. وبحسب سياسة Anthropic، لا تُستخدم المُوجِّهات والردود لتدريب نماذجها. يخزّن LightChats رد الذكاء الاصطناعي في مساحة عملك بجانب المحادثة؛ يمكنك حذف هذه البيانات عبر صندوق الوارد أو من خلال ",
    providersLink: "حذف الحساب بالكامل",
    providersAfter: ".",
    reportTitle: "الإبلاغ عن المشكلات",
    reportBefore:
      "إذا تلقّيت رسالة مولّدة بالذكاء الاصطناعي تعتقد أنها ضارة أو مضللة أو مخالفة لسياسات إنستغرام، يرجى الإبلاغ عنها إلى ",
    reportAfter:
      ". نحقّق في كل بلاغ ونعطّل التدفق المخالف خلال المراجعة.",
  },
};
