import type { Lang } from "../LanguageContext";

interface SecurityContent {
  eyebrow: string;
  title: string;
  intro: string;
  authTitle: string;
  authBullets: string[];
  dataTitle: string;
  dataBullets: string[];
  permsTitle: string;
  permsIntro: string;
  permsRead: { label: string; desc: string };
  permsSend: { label: string; desc: string };
  permsReadComments: { label: string; desc: string };
  permsManage: { label: string; desc: string };
  permsOutro: string;
  paymentTitle: string;
  paymentBullets: { prefix?: string; brand?: string; suffix?: string; full?: string }[];
  aiTitle: string;
  aiBody: string;
  vulnTitle: string;
  vulnBody1: string; // before email
  vulnBody2: string; // between email and quoted subject
  vulnSubject: string;
  vulnBody3: string; // after
  deletionTitle: string;
  deletionBody1: string;
  deletionLink: string;
  deletionBody2: string;
}

export const security: Record<Lang, SecurityContent> = {
  en: {
    eyebrow: "Security",
    title: "How we keep your data safe",
    intro:
      "A practical overview of LightChats' security posture — what data we store, where it lives, and how we protect it.",
    authTitle: "Authentication",
    authBullets: [
      "Instagram is connected via Meta's official OAuth flow. We never see, store, or transmit your Instagram password.",
      "LightChats accounts use email + password with bcrypt-hashed credentials. Passwords are never stored in plaintext.",
      "Sessions expire after 30 days of inactivity and can be revoked from any device.",
    ],
    dataTitle: "Data in transit and at rest",
    dataBullets: [
      "All traffic is TLS 1.3 with HSTS. The app does not load over plain HTTP.",
      "Database is encrypted at rest using AES-256.",
      "Backups are encrypted with separate keys and rotated daily.",
    ],
    permsTitle: "Instagram permissions we request",
    permsIntro:
      "LightChats requests only the OAuth scopes it needs to do its job. You can review these on the Instagram authorization screen before connecting:",
    permsRead: {
      label: "Read messages",
      desc: " — to see incoming DMs and trigger flows",
    },
    permsSend: {
      label: "Send messages",
      desc: " — to send the responses your flows define",
    },
    permsReadComments: {
      label: "Read comments",
      desc: " — to detect comment-trigger keywords",
    },
    permsManage: {
      label: "Manage comments",
      desc: " — only if you enable comment auto-reply or hide-spam features",
    },
    permsOutro:
      "We never request access to your follower list, audience insights, or ad accounts.",
    paymentTitle: "Payment data",
    paymentBullets: [
      {
        prefix: "All card data is handled by ",
        brand: "Stripe",
        suffix:
          " (PCI-DSS Level 1). LightChats never sees your full card number.",
      },
      {
        full:
          "Subscriptions and auto top-ups are charged automatically; receipts are emailed for every charge.",
      },
      {
        full:
          "You can remove your saved card anytime from Billing — the only side-effect is that auto top-ups stop working.",
      },
    ],
    aiTitle: "AI provider data handling",
    aiBody:
      "AI replies and conversations are generated by Anthropic's Claude API. Per Anthropic's policy, prompts and responses sent through the API are not used to train Anthropic models. The full content of an AI conversation is stored in your LightChats workspace — you can review and delete it from the Inbox.",
    vulnTitle: "Vulnerability reporting",
    vulnBody1:
      "We take security reports seriously and respond within 24 hours. Email ",
    vulnBody2: " with the subject ",
    vulnSubject: '"Security Disclosure"',
    vulnBody3:
      ". Please do not publicly disclose vulnerabilities before we've had a chance to investigate and patch.",
    deletionTitle: "Data deletion",
    deletionBody1:
      "You can delete your account and all associated data at any time. See the ",
    deletionLink: "Data Deletion",
    deletionBody2: " page for the full process.",
  },
  fr: {
    eyebrow: "Sécurité",
    title: "Comment nous protégeons vos données",
    intro:
      "Un aperçu concret de la posture de sécurité de LightChats — quelles données nous stockons, où elles résident et comment nous les protégeons.",
    authTitle: "Authentification",
    authBullets: [
      "Instagram est connecté via le flux OAuth officiel de Meta. Nous ne voyons, ne stockons et ne transmettons jamais votre mot de passe Instagram.",
      "Les comptes LightChats utilisent un e-mail et un mot de passe avec des identifiants hachés via bcrypt. Les mots de passe ne sont jamais stockés en clair.",
      "Les sessions expirent après 30 jours d'inactivité et peuvent être révoquées depuis n'importe quel appareil.",
    ],
    dataTitle: "Données en transit et au repos",
    dataBullets: [
      "Tout le trafic utilise TLS 1.3 avec HSTS. L'application ne se charge jamais en HTTP simple.",
      "La base de données est chiffrée au repos avec AES-256.",
      "Les sauvegardes sont chiffrées avec des clés distinctes et renouvelées chaque jour.",
    ],
    permsTitle: "Autorisations Instagram demandées",
    permsIntro:
      "LightChats ne demande que les scopes OAuth nécessaires à son fonctionnement. Vous pouvez les vérifier sur l'écran d'autorisation Instagram avant de connecter votre compte :",
    permsRead: {
      label: "Lecture des messages",
      desc: " — pour recevoir les DM entrants et déclencher les flux",
    },
    permsSend: {
      label: "Envoi de messages",
      desc: " — pour envoyer les réponses définies par vos flux",
    },
    permsReadComments: {
      label: "Lecture des commentaires",
      desc: " — pour détecter les mots-clés déclencheurs",
    },
    permsManage: {
      label: "Gestion des commentaires",
      desc: " — uniquement si vous activez la réponse automatique aux commentaires ou le masquage des spams",
    },
    permsOutro:
      "Nous ne demandons jamais l'accès à votre liste d'abonnés, à vos insights d'audience ou à vos comptes publicitaires.",
    paymentTitle: "Données de paiement",
    paymentBullets: [
      {
        prefix: "Toutes les données de carte sont traitées par ",
        brand: "Stripe",
        suffix:
          " (PCI-DSS niveau 1). LightChats ne voit jamais votre numéro de carte complet.",
      },
      {
        full:
          "Les abonnements et recharges automatiques sont prélevés automatiquement ; un reçu est envoyé par e-mail à chaque prélèvement.",
      },
      {
        full:
          "Vous pouvez supprimer votre carte enregistrée à tout moment depuis Facturation — la seule conséquence est que les recharges automatiques cessent.",
      },
    ],
    aiTitle: "Traitement des données par le fournisseur d'IA",
    aiBody:
      "Les réponses et conversations IA sont générées par l'API Claude d'Anthropic. Selon la politique d'Anthropic, les requêtes et réponses envoyées via l'API ne sont pas utilisées pour entraîner les modèles d'Anthropic. Le contenu complet d'une conversation IA est conservé dans votre espace LightChats — vous pouvez le consulter et le supprimer depuis la boîte de réception.",
    vulnTitle: "Signalement de vulnérabilités",
    vulnBody1:
      "Nous prenons les signalements de sécurité au sérieux et répondons sous 24 heures. Envoyez un e-mail à ",
    vulnBody2: " avec l'objet ",
    vulnSubject: "« Security Disclosure »",
    vulnBody3:
      ". Merci de ne pas divulguer publiquement une vulnérabilité avant que nous ayons eu le temps de l'analyser et de la corriger.",
    deletionTitle: "Suppression de données",
    deletionBody1:
      "Vous pouvez supprimer votre compte et toutes les données associées à tout moment. Consultez la page ",
    deletionLink: "Suppression de données",
    deletionBody2: " pour la procédure complète.",
  },
  ar: {
    eyebrow: "الأمان",
    title: "كيف نحافظ على أمان بياناتك",
    intro:
      "نظرة عملية على منظومة الأمان في LightChats — ما البيانات التي نخزّنها، وأين تُحفظ، وكيف نحميها.",
    authTitle: "المصادقة",
    authBullets: [
      "يتم ربط إنستغرام عبر تدفق OAuth الرسمي من Meta. لا نرى كلمة مرور إنستغرام الخاصة بك ولا نخزّنها ولا ننقلها أبداً.",
      "تستخدم حسابات LightChats البريد الإلكتروني وكلمة المرور مع تجزئة بياناتك بخوارزمية bcrypt. لا تُخزَّن كلمات المرور كنص واضح أبداً.",
      "تنتهي الجلسات بعد 30 يوماً من عدم النشاط، ويمكن إلغاؤها من أي جهاز.",
    ],
    dataTitle: "البيانات أثناء النقل والتخزين",
    dataBullets: [
      "كل حركة المرور تمر عبر TLS 1.3 مع HSTS. لا يعمل التطبيق عبر HTTP عادي.",
      "قاعدة البيانات مشفّرة عند التخزين باستخدام AES-256.",
      "النسخ الاحتياطية مشفّرة بمفاتيح منفصلة ويتم تدويرها يومياً.",
    ],
    permsTitle: "أذونات إنستغرام التي نطلبها",
    permsIntro:
      "يطلب LightChats فقط نطاقات OAuth الضرورية لأداء عمله. يمكنك مراجعتها على شاشة منح الأذونات في إنستغرام قبل ربط حسابك:",
    permsRead: {
      label: "قراءة الرسائل",
      desc: " — لرؤية الرسائل الواردة وتشغيل التدفقات",
    },
    permsSend: {
      label: "إرسال الرسائل",
      desc: " — لإرسال الردود التي تحدّدها تدفقاتك",
    },
    permsReadComments: {
      label: "قراءة التعليقات",
      desc: " — لاكتشاف الكلمات المفتاحية المحفّزة",
    },
    permsManage: {
      label: "إدارة التعليقات",
      desc: " — فقط إذا فعّلت الرد التلقائي على التعليقات أو إخفاء الرسائل المزعجة",
    },
    permsOutro:
      "لا نطلب أبداً الوصول إلى قائمة متابعيك أو إحصاءات جمهورك أو حسابات الإعلانات.",
    paymentTitle: "بيانات الدفع",
    paymentBullets: [
      {
        prefix: "تتم معالجة جميع بيانات البطاقات بواسطة ",
        brand: "Stripe",
        suffix:
          " (PCI-DSS من المستوى 1). لا يرى LightChats رقم بطاقتك كاملاً أبداً.",
      },
      {
        full:
          "تُحصَّل الاشتراكات والشحنات التلقائية تلقائياً، ويُرسَل إيصال بالبريد عند كل عملية.",
      },
      {
        full:
          "يمكنك إزالة البطاقة المحفوظة في أي وقت من صفحة الفواتير — النتيجة الوحيدة هي توقّف الشحن التلقائي.",
      },
    ],
    aiTitle: "تعامل مزوّد الذكاء الاصطناعي مع البيانات",
    aiBody:
      "تُولَّد ردود الذكاء الاصطناعي ومحادثاته عبر واجهة Claude API من Anthropic. وفقاً لسياسة Anthropic، لا تُستخدم الطلبات والاستجابات المرسلة عبر الواجهة لتدريب نماذج Anthropic. يُحفظ المحتوى الكامل للمحادثة في مساحة عملك على LightChats — يمكنك مراجعته وحذفه من صندوق الوارد.",
    vulnTitle: "الإبلاغ عن الثغرات",
    vulnBody1:
      "نتعامل بجدّية مع البلاغات الأمنية ونردّ خلال 24 ساعة. راسلنا على ",
    vulnBody2: " مع جعل عنوان الرسالة ",
    vulnSubject: '"Security Disclosure"',
    vulnBody3:
      ". يُرجى عدم الإفصاح عن الثغرات علناً قبل أن تتاح لنا الفرصة لمعالجتها وتصحيحها.",
    deletionTitle: "حذف البيانات",
    deletionBody1:
      "يمكنك حذف حسابك وجميع البيانات المرتبطة به في أي وقت. اطّلع على صفحة ",
    deletionLink: "حذف البيانات",
    deletionBody2: " للإجراء الكامل.",
  },
};
